// Alert — domain event emitted when the safety logic fires.
// Serialisation lives in the infrastructure layer (WebSocketAlertPublisher).

#ifndef FORKLIFT_DOMAIN_ALERT_H_
#define FORKLIFT_DOMAIN_ALERT_H_

#include <chrono>
#include <cstdint>
#include <string>

#include "forklift/domain/BoundingBox.h"

namespace forklift::domain {

enum class AlertType : std::uint8_t {
    kPersonNearForklift = 1,
};

enum class AlertSeverity : std::uint8_t {
    kInfo     = 0,
    kWarning  = 1,
    kCritical = 2,
};

struct Alert {
    using Clock     = std::chrono::system_clock;
    using TimePoint = Clock::time_point;

    std::string   alert_id;            // ULID/UUID, generated by use case
    std::string   camera_id;
    AlertType     type{AlertType::kPersonNearForklift};
    AlertSeverity severity{AlertSeverity::kWarning};
    TimePoint     timestamp{};
    int           person_track_id{-1};
    int           forklift_track_id{-1};
    BoundingBox   person_box{};
    BoundingBox   forklift_box{};
    BoundingBox   safety_zone_box{};
    float         distance_px{0.0F};   // 0 when person is inside the zone
};

constexpr const char* to_string(AlertType t) noexcept {
    switch (t) {
        case AlertType::kPersonNearForklift: return "person_near_forklift";
    }
    return "unknown";
}

constexpr const char* to_string(AlertSeverity s) noexcept {
    switch (s) {
        case AlertSeverity::kInfo:     return "info";
        case AlertSeverity::kWarning:  return "warning";
        case AlertSeverity::kCritical: return "critical";
    }
    return "unknown";
}

}  // namespace forklift::domain

#endif  // FORKLIFT_DOMAIN_ALERT_H_
